---
title: "🔖 Week 01 - Appendix"
subtitle: "Data Science - Key Concepts"
date: 5 September 2022
date-meta: 5 September 2022
---

## Indicative Reading

This week's indicative reading: [@james_introduction_2021, chapter 2, 2.1-2.2]

## Recommended (additional) reading

**What are different ways one can approach a modelling problem?**

Checkout the upcoming book ['Modeling Mindsets'](https://book.modeling-mindsets.com/) [@molnar_modeling_2022, chapters 2-3] (it's free to read online) to learn about the traditional frequentist statistics vs Bayesian statistics vs Machine Learning approaches.

The following twitter thread also summarises the main points of these different paradigms:
<blockquote class="twitter-tweet"><p lang="en" dir="ltr">In a perfect world, you could effortlessly switch between modeling mindsets (statistics, machine learning, causal inference, ...).<br><br>Realistically, you only have time to master a few mindsets.<br><br>So what to do? A thread 🧵</p>&mdash; Christoph Molnar (\@ChristophMolnar) <a href="https://twitter.com/ChristophMolnar/status/1564624829009072129?ref_src=twsrc%5Etfw">August 30, 2022</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>


## Digital Skills Lab

[Digital Skills Lab](https://info.lse.ac.uk/current-students/digital-skills-lab) offer R and python workshops during Term time, and they will also give DSI students access to self-paced programming courses on Dataquest.

If you want to take the self-paced course to revise basic R programming, sign up via [this link](https://lse.eu.qualtrics.com/jfe/form/SV_6DbHqit2R8Y324u).

Keep an eye on the following pages for news of the in-person workshops:
- R: https://info.lse.ac.uk/current-students/digital-skills-lab/r
- Python: https://info.lse.ac.uk/current-students/digital-skills-lab/python


## Other resources

- Checkout this summer's LSE Careers Skill Accelerator programme. Some of the self-paced courses will remain open to LSE students until the end of the year.

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Ready to develop the key skills employers are looking for in 2022?<br><br>Join this summer&#39;s LSE Careers Skills Accelerator programme to expand your skillset!<br><br>⭐Apply on CareerHub by 11.59pm, Wed 15 June for your chance to join the programme⭐<a href="https://t.co/J5sI1NRaMA">https://t.co/J5sI1NRaMA</a></p>&mdash; LSE Careers (@LSECareers) <a href="https://twitter.com/LSECareers/status/1534868470495596545?ref_src=twsrc%5Etfw">June 9, 2022</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

- The book [R for Data Science](https://r4ds.had.co.nz/) is free to read online and is a great resource to advance your R skills. 